<?php /** @var \Kamephis\Avatar\Block\Gravatar $block */ ?>

<style>
    .avatar-circle {
        display: inline-block;
        overflow: hidden;
        border-radius: 50%;
        width: 50px;
        height: 50px;
        background: #1b721a;
        border: 1px solid #1e7c1d;
    }

    .avatar-circle img {
        display: block;
        max-width: 100%;
        height: auto;
    }

    .customer-info-wrapper{
        display: flex;
        flex-direction: row;
        justify-content: flex-start;
        margin: 10px 0 20px 0;
    }
    .customer-info{
        margin-left: 20px;
    }
</style>

<div class="customer-info-wrapper">
    <div class="avatar-wrapper">
        <div class="avatar-circle">
            <img src="<?php echo $block->escapeUrl($block->getGravatarUrl()); ?>" alt="User's gravatar">
        </div>
    </div>

    <div class="customer-info">
        <b>
        <?= __('Hello');?> <?= $block->escapeUrl($block->customerHelper->getCustomerAttribute('firstname')); ?>
        </b><br>
        <?= __('Last login: ');?><br>
        <span class="last-login-date-block"></span>
        <br><br>
        <a href="<?= $block->getUrl('customer/account/logout'); ?>"><?= __('Sign Out') ?></a>
    </div>
</div>

<script>
    window.addEventListener('load', function() {
        var xhr = new XMLHttpRequest();
        xhr.open('GET', '<?= $block->getUrl("kamephis_avatar/avatar/index") ?>', true);
        xhr.onload = function() {
            if (xhr.readyState === xhr.DONE) {
                if (xhr.status === 200) {
                    var response = JSON.parse(xhr.responseText);
                    document.querySelector('.last-login-date-block').innerHTML = response.last_login_date;
                } else {
                    console.error("AJAX Error: " + xhr.statusText);
                }
            }
        };
        xhr.onerror = function() {
            console.error("AJAX Error: " + xhr.statusText);
        };
        xhr.send();
    });
</script>


