<?php /** @var \Kamephis\Avatar\Block\Gravatar $block */ ?>

<style>
    .avatar-circle {
        display: inline-block;
        overflow: hidden;
        border-radius: 50%;
        width: 80px;
        height: 80px;
        background: #1b721a;
        border: 1px solid #1e7c1d;
    }

    .avatar-circle img {
        display: block;
        max-width: 100%;
        height: auto;
    }

    .customer-info-wrapper{
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        margin: 10px 0 20px 0;
    }


</style>
<div class="customer-info-wrapper">
    <div class="avatar-wrapper">
        <div class="avatar-circle">
            <img src="<?php echo $block->escapeUrl($block->getGravatarUrl()); ?>" alt="User's gravatar">
        </div>
    </div>

    <div class="customer-info">
        <?= $block->escapeUrl($block->customerHelper->getCustomerAttribute('firstname')); ?>
        <?= $block->escapeUrl($block->customerHelper->getCustomerAttribute('lastname')); ?><br>
        <?= $block->escapeUrl($block->customerHelper->getCustomerAttribute('email')); ?><br>
        <?= __('Last login: ');?><br>
        <?php echo $block->customerHelper->getCustomerLastLoginDate(); ?><br>
    </div>
</div>

