<?php /** @var \Kamephis\Avatar\Block\Gravatar $block */ ?>

<style>
    .avatar-circle {
        display: inline-block;
        overflow: hidden;
        border-radius: 50%;
        width: 50px;
        height: 50px;
        background: #1b721a;
        border: 1px solid #1e7c1d;
    }

    .avatar-circle img {
        display: block;
        max-width: 100%;
        height: auto;
    }

    .customer-info-wrapper{
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        margin: 10px 0 20px 0;
    }


</style>
<!--
<div class="customer-info-wrapper">
    <div class="avatar-wrapper">
        <div class="avatar-circle">
            <img src="<?php echo $block->escapeUrl($block->getGravatarUrl()); ?>" alt="User's gravatar">
        </div>
    </div>

    <div class="customer-info">
        <b>
        <?= $block->escapeUrl($block->customerHelper->getCustomerAttribute('firstname')); ?>
        <?= $block->escapeUrl($block->customerHelper->getCustomerAttribute('lastname')); ?>
        </b><br>
        <?= __('Last login: ');?>
        <?php echo $block->customerHelper->getCustomerLastLoginDate(); ?><br>
        <a href="<?= $block->getUrl('customer/account/logout'); ?>"><?= __('Sign Out') ?></a>
    </div>
</div>
-->

<div data-bind="html: avatarHtml"></div>

<script type="text/javascript">
    require([
        'jquery',
        'ko',
        'mage/url',
    ], function ($, ko, urlBuilder) {

        var customerAvatar = {
            avatarHtml: ko.observable(),
            init: function () {
                var ajaxUrl = urlBuilder.build('avatar/index/index');
                var self = this;
                $.ajax({
                    url: ajaxUrl,
                    type: 'POST',
                    dataType: 'json',
                    success: function (response) {
                        self.avatarHtml(response.avatarHtml);
                    }
                });
            }
        };
        customerAvatar.init();
        ko.applyBindings(customerAvatar);
    });
</script>

